/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as amb from "./amb";
export type { amb };
import type * as ethereum from "./ethereum";
export type { ethereum };
import type * as interfaces from "./interfaces";
export type { interfaces };
import type * as libraries from "./libraries";
export type { libraries };
import type * as oracle from "./oracle";
export type { oracle };
