/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ReceiverStorage__factory } from "./ReceiverStorage__factory";
export { SenderStorage__factory } from "./SenderStorage__factory";
export { SharedStorage__factory } from "./SharedStorage__factory";
