/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  SharedStorage,
  SharedStorageInterface,
} from "../../../../contracts/amb/LoremIpsumStorage.sol/SharedStorage";

const _abi = [
  {
    inputs: [],
    name: "version",
    outputs: [
      {
        internalType: "uint8",
        name: "",
        type: "uint8",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class SharedStorage__factory {
  static readonly abi = _abi;
  static createInterface(): SharedStorageInterface {
    return new utils.Interface(_abi) as SharedStorageInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): SharedStorage {
    return new Contract(address, _abi, signerOrProvider) as SharedStorage;
  }
}
