/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../../../common";

export interface IExecuteMessageTransitionHandlerInterface
  extends utils.Interface {
  functions: {
    "processExecuteMessageCrossChain(uint64,uint32,address,uint32,address,bytes)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: "processExecuteMessageCrossChain"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "processExecuteMessageCrossChain",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>,
      PromiseOrValue<BytesLike>
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "processExecuteMessageCrossChain",
    data: BytesLike
  ): Result;

  events: {};
}

export interface IExecuteMessageTransitionHandler extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IExecuteMessageTransitionHandlerInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    processExecuteMessageCrossChain(
      _nonce: PromiseOrValue<BigNumberish>,
      _sourceChainId: PromiseOrValue<BigNumberish>,
      _sourceAddress: PromiseOrValue<string>,
      _destinationChainId: PromiseOrValue<BigNumberish>,
      _destinationAddress: PromiseOrValue<string>,
      _transitionStorageRawData: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  processExecuteMessageCrossChain(
    _nonce: PromiseOrValue<BigNumberish>,
    _sourceChainId: PromiseOrValue<BigNumberish>,
    _sourceAddress: PromiseOrValue<string>,
    _destinationChainId: PromiseOrValue<BigNumberish>,
    _destinationAddress: PromiseOrValue<string>,
    _transitionStorageRawData: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    processExecuteMessageCrossChain(
      _nonce: PromiseOrValue<BigNumberish>,
      _sourceChainId: PromiseOrValue<BigNumberish>,
      _sourceAddress: PromiseOrValue<string>,
      _destinationChainId: PromiseOrValue<BigNumberish>,
      _destinationAddress: PromiseOrValue<string>,
      _transitionStorageRawData: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    processExecuteMessageCrossChain(
      _nonce: PromiseOrValue<BigNumberish>,
      _sourceChainId: PromiseOrValue<BigNumberish>,
      _sourceAddress: PromiseOrValue<string>,
      _destinationChainId: PromiseOrValue<BigNumberish>,
      _destinationAddress: PromiseOrValue<string>,
      _transitionStorageRawData: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    processExecuteMessageCrossChain(
      _nonce: PromiseOrValue<BigNumberish>,
      _sourceChainId: PromiseOrValue<BigNumberish>,
      _sourceAddress: PromiseOrValue<string>,
      _destinationChainId: PromiseOrValue<BigNumberish>,
      _destinationAddress: PromiseOrValue<string>,
      _transitionStorageRawData: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
