/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IExecuteMessageTransitionHandler } from "./IExecuteMessageTransitionHandler";
export type { ILoremIpsumReceiver } from "./ILoremIpsumReceiver";
export type { ILoremIpsumRequestHandler } from "./ILoremIpsumRequestHandler";
export type { ILoremIpsumResonseHandler } from "./ILoremIpsumResonseHandler";
export type { ILoremIpsumSender } from "./ILoremIpsumSender";
