/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as zkOracleSol from "./zkOracle.sol";
export { LoremIpsumOracle__factory } from "./LoremIpsumOracle__factory";
