/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  SubscriptionReceiver,
  SubscriptionReceiverInterface,
} from "../../../../contracts/pubsub/interfaces/SubscriptionReceiver";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "sender",
        type: "address",
      },
    ],
    name: "NotFromLoremIpsumPubSub",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "_subscriptionId",
        type: "bytes32",
      },
      {
        internalType: "uint32",
        name: "_sourceChainId",
        type: "uint32",
      },
      {
        internalType: "address",
        name: "_sourceAddress",
        type: "address",
      },
      {
        internalType: "uint64",
        name: "_slot",
        type: "uint64",
      },
      {
        internalType: "bytes32[]",
        name: "_eventTopics",
        type: "bytes32[]",
      },
      {
        internalType: "bytes",
        name: "_eventdata",
        type: "bytes",
      },
    ],
    name: "handlePublish",
    outputs: [
      {
        internalType: "bytes4",
        name: "",
        type: "bytes4",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "pubSub",
    outputs: [
      {
        internalType: "contract LoremIpsumPubSub",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class SubscriptionReceiver__factory {
  static readonly abi = _abi;
  static createInterface(): SubscriptionReceiverInterface {
    return new utils.Interface(_abi) as SubscriptionReceiverInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): SubscriptionReceiver {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as SubscriptionReceiver;
  }
}
