/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  ILoremIpsumResonseHandler,
  ILoremIpsumResonseHandlerInterface,
} from "../../../../../contracts/amb/interfaces/ILoremIpsum.sol/ILoremIpsumResonseHandler";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint32",
        name: "_sourceChainId",
        type: "uint32",
      },
      {
        internalType: "address",
        name: "_sourceAddress",
        type: "address",
      },
      {
        internalType: "bytes",
        name: "_data",
        type: "bytes",
      },
    ],
    name: "handleResponseMessage",
    outputs: [
      {
        internalType: "bytes4",
        name: "",
        type: "bytes4",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class ILoremIpsumResonseHandler__factory {
  static readonly abi = _abi;
  static createInterface(): ILoremIpsumResonseHandlerInterface {
    return new utils.Interface(_abi) as ILoremIpsumResonseHandlerInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ILoremIpsumResonseHandler {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as ILoremIpsumResonseHandler;
  }
}
