/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IncomeHandler,
  IncomeHandlerInterface,
} from "../../../../../contracts/amb/interfaces/ILoremIpsum.sol/IncomeHandler";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint64",
        name: "_nonce",
        type: "uint64",
      },
      {
        internalType: "uint32",
        name: "_sourceChainId",
        type: "uint32",
      },
      {
        internalType: "address",
        name: "_sourceAddress",
        type: "address",
      },
      {
        internalType: "uint32",
        name: "_destinationChainId",
        type: "uint32",
      },
      {
        internalType: "address",
        name: "_destinationAddress",
        type: "address",
      },
      {
        internalType: "bytes",
        name: "_transitionStorageRawData",
        type: "bytes",
      },
    ],
    name: "enqueue",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IncomeHandler__factory {
  static readonly abi = _abi;
  static createInterface(): IncomeHandlerInterface {
    return new utils.Interface(_abi) as IncomeHandlerInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IncomeHandler {
    return new Contract(address, _abi, signerOrProvider) as IncomeHandler;
  }
}
