/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ILayerZeroEndpoint } from "./ILayerZeroEndpoint";
export type { ILayerZeroOracleV2 } from "./ILayerZeroOracleV2";
export type { ILayerZeroUltraLightNodeV2 } from "./ILayerZeroUltraLightNodeV2";
export type { IProtocolState } from "./IProtocolState";
