/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as evmLoremIpsum from "./evm-lorem-ipsum";
export * as evmPlaceholderVerification from "./evm-placeholder-verification";
