/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as interfaces from "./interfaces";
export { LoremIpsumPubSub__factory } from "./LoremIpsumPubSub__factory";
export { LoremIpsumPublisher__factory } from "./LoremIpsumPublisher__factory";
export { LoremIpsumSubscriber__factory } from "./LoremIpsumSubscriber__factory";
export { PubSubStorage__factory } from "./PubSubStorage__factory";
