/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { MockLoremIpsum__factory } from "./MockLoremIpsum__factory";
export { MockSourceAMB__factory } from "./MockSourceAMB__factory";
export { MockTargetAMB__factory } from "./MockTargetAMB__factory";
