/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ReceiverStorage } from "./ReceiverStorage";
export type { SenderStorage } from "./SenderStorage";
export type { SharedStorage } from "./SharedStorage";
