/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "../../../common";

export interface SenderStorageInterface extends utils.Interface {
  functions: {
    "nonce()": FunctionFragment;
    "sendingEnabled()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: "nonce" | "sendingEnabled"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "nonce", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "sendingEnabled",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "nonce", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "sendingEnabled",
    data: BytesLike
  ): Result;

  events: {};
}

export interface SenderStorage extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: SenderStorageInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    nonce(overrides?: CallOverrides): Promise<[BigNumber]>;

    sendingEnabled(overrides?: CallOverrides): Promise<[boolean]>;
  };

  nonce(overrides?: CallOverrides): Promise<BigNumber>;

  sendingEnabled(overrides?: CallOverrides): Promise<boolean>;

  callStatic: {
    nonce(overrides?: CallOverrides): Promise<BigNumber>;

    sendingEnabled(overrides?: CallOverrides): Promise<boolean>;
  };

  filters: {};

  estimateGas: {
    nonce(overrides?: CallOverrides): Promise<BigNumber>;

    sendingEnabled(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    nonce(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    sendingEnabled(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
