/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../../../common";

export type SubscriptionStruct = {
  sourceChainId: PromiseOrValue<BigNumberish>;
  sourceAddress: PromiseOrValue<string>;
  callbackAddress: PromiseOrValue<string>;
  eventSig: PromiseOrValue<BytesLike>;
};

export type SubscriptionStructOutput = [number, string, string, string] & {
  sourceChainId: number;
  sourceAddress: string;
  callbackAddress: string;
  eventSig: string;
};

export interface IPublisherInterface extends utils.Interface {
  functions: {
    "publishEvent(bytes,bytes32[],bytes32,bytes[],bytes,uint256,(uint32,address,address,bytes32))": FunctionFragment;
  };

  getFunction(nameOrSignatureOrTopic: "publishEvent"): FunctionFragment;

  encodeFunctionData(
    functionFragment: "publishEvent",
    values: [
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>[],
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>[],
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BigNumberish>,
      SubscriptionStruct
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "publishEvent",
    data: BytesLike
  ): Result;

  events: {
    "Publish(bytes32,uint32,address,address,bool)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "Publish"): EventFragment;
}

export interface PublishEventObject {
  subscriptionId: string;
  sourceChainId: number;
  sourceAddress: string;
  callbackAddress: string;
  success: boolean;
}
export type PublishEvent = TypedEvent<
  [string, number, string, string, boolean],
  PublishEventObject
>;

export type PublishEventFilter = TypedEventFilter<PublishEvent>;

export interface IPublisher extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IPublisherInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    publishEvent(
      srcSlotTxSlotPack: PromiseOrValue<BytesLike>,
      receiptsRootProof: PromiseOrValue<BytesLike>[],
      receiptsRoot: PromiseOrValue<BytesLike>,
      receiptProof: PromiseOrValue<BytesLike>[],
      txIndexRLPEncoded: PromiseOrValue<BytesLike>,
      logIndex: PromiseOrValue<BigNumberish>,
      subscription: SubscriptionStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  publishEvent(
    srcSlotTxSlotPack: PromiseOrValue<BytesLike>,
    receiptsRootProof: PromiseOrValue<BytesLike>[],
    receiptsRoot: PromiseOrValue<BytesLike>,
    receiptProof: PromiseOrValue<BytesLike>[],
    txIndexRLPEncoded: PromiseOrValue<BytesLike>,
    logIndex: PromiseOrValue<BigNumberish>,
    subscription: SubscriptionStruct,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    publishEvent(
      srcSlotTxSlotPack: PromiseOrValue<BytesLike>,
      receiptsRootProof: PromiseOrValue<BytesLike>[],
      receiptsRoot: PromiseOrValue<BytesLike>,
      receiptProof: PromiseOrValue<BytesLike>[],
      txIndexRLPEncoded: PromiseOrValue<BytesLike>,
      logIndex: PromiseOrValue<BigNumberish>,
      subscription: SubscriptionStruct,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "Publish(bytes32,uint32,address,address,bool)"(
      subscriptionId?: PromiseOrValue<BytesLike> | null,
      sourceChainId?: PromiseOrValue<BigNumberish> | null,
      sourceAddress?: PromiseOrValue<string> | null,
      callbackAddress?: null,
      success?: null
    ): PublishEventFilter;
    Publish(
      subscriptionId?: PromiseOrValue<BytesLike> | null,
      sourceChainId?: PromiseOrValue<BigNumberish> | null,
      sourceAddress?: PromiseOrValue<string> | null,
      callbackAddress?: null,
      success?: null
    ): PublishEventFilter;
  };

  estimateGas: {
    publishEvent(
      srcSlotTxSlotPack: PromiseOrValue<BytesLike>,
      receiptsRootProof: PromiseOrValue<BytesLike>[],
      receiptsRoot: PromiseOrValue<BytesLike>,
      receiptProof: PromiseOrValue<BytesLike>[],
      txIndexRLPEncoded: PromiseOrValue<BytesLike>,
      logIndex: PromiseOrValue<BigNumberish>,
      subscription: SubscriptionStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    publishEvent(
      srcSlotTxSlotPack: PromiseOrValue<BytesLike>,
      receiptsRootProof: PromiseOrValue<BytesLike>[],
      receiptsRoot: PromiseOrValue<BytesLike>,
      receiptProof: PromiseOrValue<BytesLike>[],
      txIndexRLPEncoded: PromiseOrValue<BytesLike>,
      logIndex: PromiseOrValue<BigNumberish>,
      subscription: SubscriptionStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
