/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IProtocolState } from "./IProtocolState";
export type { IZKLightClient } from "./IZKLightClient";
