/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../../../common";

export type LightClientUpdateStruct = {
  attestedSlot: PromiseOrValue<BigNumberish>;
  finalizedSlot: PromiseOrValue<BigNumberish>;
  participation: PromiseOrValue<BigNumberish>;
  finalizedHeaderRoot: PromiseOrValue<BytesLike>;
  executionStateRoot: PromiseOrValue<BytesLike>;
  proof: PromiseOrValue<BytesLike>;
};

export type LightClientUpdateStructOutput = [
  BigNumber,
  BigNumber,
  BigNumber,
  string,
  string,
  string
] & {
  attestedSlot: BigNumber;
  finalizedSlot: BigNumber;
  participation: BigNumber;
  finalizedHeaderRoot: string;
  executionStateRoot: string;
  proof: string;
};

export interface IZKLightClientInterface extends utils.Interface {
  functions: {
    "step((uint256,uint256,uint256,bytes32,bytes32,bytes))": FunctionFragment;
  };

  getFunction(nameOrSignatureOrTopic: "step"): FunctionFragment;

  encodeFunctionData(
    functionFragment: "step",
    values: [LightClientUpdateStruct]
  ): string;

  decodeFunctionResult(functionFragment: "step", data: BytesLike): Result;

  events: {};
}

export interface IZKLightClient extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IZKLightClientInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    step(
      update: LightClientUpdateStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  step(
    update: LightClientUpdateStruct,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    step(
      update: LightClientUpdateStruct,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    step(
      update: LightClientUpdateStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    step(
      update: LightClientUpdateStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
