/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { MockLoremIpsum } from "./MockLoremIpsum";
export type { MockSourceAMB } from "./MockSourceAMB";
export type { MockTargetAMB } from "./MockTargetAMB";
