/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as interfaces from "./interfaces";
export * as loremIpsum from "./lorem-ipsum";
export * as mocks from "./mocks";
export * as oracle from "./oracle";
