/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as interfaces from "./interfaces";
export type { interfaces };
export type { LoremIpsumPubSub } from "./LoremIpsumPubSub";
export type { LoremIpsumPublisher } from "./LoremIpsumPublisher";
export type { LoremIpsumSubscriber } from "./LoremIpsumSubscriber";
export type { PubSubStorage } from "./PubSubStorage";
