/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../common";

export type SubscriptionStruct = {
  sourceChainId: PromiseOrValue<BigNumberish>;
  sourceAddress: PromiseOrValue<string>;
  callbackAddress: PromiseOrValue<string>;
  eventSig: PromiseOrValue<BytesLike>;
};

export type SubscriptionStructOutput = [number, string, string, string] & {
  sourceChainId: number;
  sourceAddress: string;
  callbackAddress: string;
  eventSig: string;
};

export interface LoremIpsumPubSubInterface extends utils.Interface {
  functions: {
    "VERSION()": FunctionFragment;
    "eventsPublished(bytes32)": FunctionFragment;
    "publishEvent(bytes,bytes32[],bytes32,bytes[],bytes,uint256,(uint32,address,address,bytes32))": FunctionFragment;
    "subscribe(uint32,address,address,bytes32,uint64,uint64)": FunctionFragment;
    "subscriptions(bytes32)": FunctionFragment;
    "unsubscribe(uint32,address,bytes32)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "VERSION"
      | "eventsPublished"
      | "publishEvent"
      | "subscribe"
      | "subscriptions"
      | "unsubscribe"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "VERSION", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "eventsPublished",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "publishEvent",
    values: [
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>[],
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>[],
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BigNumberish>,
      SubscriptionStruct
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "subscribe",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "subscriptions",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "unsubscribe",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>,
      PromiseOrValue<BytesLike>
    ]
  ): string;

  decodeFunctionResult(functionFragment: "VERSION", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "eventsPublished",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "publishEvent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "subscribe", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "subscriptions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "unsubscribe",
    data: BytesLike
  ): Result;

  events: {
    "Publish(bytes32,uint32,address,address,bool)": EventFragment;
    "Subscribe(bytes32,uint64,uint64,tuple)": EventFragment;
    "Unsubscribe(bytes32,tuple)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "Publish"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Subscribe"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Unsubscribe"): EventFragment;
}

export interface PublishEventObject {
  subscriptionId: string;
  sourceChainId: number;
  sourceAddress: string;
  callbackAddress: string;
  success: boolean;
}
export type PublishEvent = TypedEvent<
  [string, number, string, string, boolean],
  PublishEventObject
>;

export type PublishEventFilter = TypedEventFilter<PublishEvent>;

export interface SubscribeEventObject {
  subscriptionId: string;
  startSlot: BigNumber;
  endSlot: BigNumber;
  subscription: SubscriptionStructOutput;
}
export type SubscribeEvent = TypedEvent<
  [string, BigNumber, BigNumber, SubscriptionStructOutput],
  SubscribeEventObject
>;

export type SubscribeEventFilter = TypedEventFilter<SubscribeEvent>;

export interface UnsubscribeEventObject {
  subscriptionId: string;
  subscription: SubscriptionStructOutput;
}
export type UnsubscribeEvent = TypedEvent<
  [string, SubscriptionStructOutput],
  UnsubscribeEventObject
>;

export type UnsubscribeEventFilter = TypedEventFilter<UnsubscribeEvent>;

export interface LoremIpsumPubSub extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: LoremIpsumPubSubInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    VERSION(overrides?: CallOverrides): Promise<[number]>;

    eventsPublished(
      arg0: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[number]>;

    publishEvent(
      srcSlotTxSlotPack: PromiseOrValue<BytesLike>,
      receiptsRootProof: PromiseOrValue<BytesLike>[],
      receiptsRoot: PromiseOrValue<BytesLike>,
      receiptProof: PromiseOrValue<BytesLike>[],
      txIndexRLPEncoded: PromiseOrValue<BytesLike>,
      logIndex: PromiseOrValue<BigNumberish>,
      subscription: SubscriptionStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    subscribe(
      _sourceChainId: PromiseOrValue<BigNumberish>,
      _sourceAddress: PromiseOrValue<string>,
      _callbackAddress: PromiseOrValue<string>,
      _eventSig: PromiseOrValue<BytesLike>,
      _startSlot: PromiseOrValue<BigNumberish>,
      _endSlot: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    subscriptions(
      arg0: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[number]>;

    unsubscribe(
      _sourceChainId: PromiseOrValue<BigNumberish>,
      _sourceAddress: PromiseOrValue<string>,
      _eventSig: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  VERSION(overrides?: CallOverrides): Promise<number>;

  eventsPublished(
    arg0: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<number>;

  publishEvent(
    srcSlotTxSlotPack: PromiseOrValue<BytesLike>,
    receiptsRootProof: PromiseOrValue<BytesLike>[],
    receiptsRoot: PromiseOrValue<BytesLike>,
    receiptProof: PromiseOrValue<BytesLike>[],
    txIndexRLPEncoded: PromiseOrValue<BytesLike>,
    logIndex: PromiseOrValue<BigNumberish>,
    subscription: SubscriptionStruct,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  subscribe(
    _sourceChainId: PromiseOrValue<BigNumberish>,
    _sourceAddress: PromiseOrValue<string>,
    _callbackAddress: PromiseOrValue<string>,
    _eventSig: PromiseOrValue<BytesLike>,
    _startSlot: PromiseOrValue<BigNumberish>,
    _endSlot: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  subscriptions(
    arg0: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<number>;

  unsubscribe(
    _sourceChainId: PromiseOrValue<BigNumberish>,
    _sourceAddress: PromiseOrValue<string>,
    _eventSig: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    VERSION(overrides?: CallOverrides): Promise<number>;

    eventsPublished(
      arg0: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<number>;

    publishEvent(
      srcSlotTxSlotPack: PromiseOrValue<BytesLike>,
      receiptsRootProof: PromiseOrValue<BytesLike>[],
      receiptsRoot: PromiseOrValue<BytesLike>,
      receiptProof: PromiseOrValue<BytesLike>[],
      txIndexRLPEncoded: PromiseOrValue<BytesLike>,
      logIndex: PromiseOrValue<BigNumberish>,
      subscription: SubscriptionStruct,
      overrides?: CallOverrides
    ): Promise<void>;

    subscribe(
      _sourceChainId: PromiseOrValue<BigNumberish>,
      _sourceAddress: PromiseOrValue<string>,
      _callbackAddress: PromiseOrValue<string>,
      _eventSig: PromiseOrValue<BytesLike>,
      _startSlot: PromiseOrValue<BigNumberish>,
      _endSlot: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>;

    subscriptions(
      arg0: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<number>;

    unsubscribe(
      _sourceChainId: PromiseOrValue<BigNumberish>,
      _sourceAddress: PromiseOrValue<string>,
      _eventSig: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<string>;
  };

  filters: {
    "Publish(bytes32,uint32,address,address,bool)"(
      subscriptionId?: PromiseOrValue<BytesLike> | null,
      sourceChainId?: PromiseOrValue<BigNumberish> | null,
      sourceAddress?: PromiseOrValue<string> | null,
      callbackAddress?: null,
      success?: null
    ): PublishEventFilter;
    Publish(
      subscriptionId?: PromiseOrValue<BytesLike> | null,
      sourceChainId?: PromiseOrValue<BigNumberish> | null,
      sourceAddress?: PromiseOrValue<string> | null,
      callbackAddress?: null,
      success?: null
    ): PublishEventFilter;

    "Subscribe(bytes32,uint64,uint64,tuple)"(
      subscriptionId?: PromiseOrValue<BytesLike> | null,
      startSlot?: PromiseOrValue<BigNumberish> | null,
      endSlot?: PromiseOrValue<BigNumberish> | null,
      subscription?: null
    ): SubscribeEventFilter;
    Subscribe(
      subscriptionId?: PromiseOrValue<BytesLike> | null,
      startSlot?: PromiseOrValue<BigNumberish> | null,
      endSlot?: PromiseOrValue<BigNumberish> | null,
      subscription?: null
    ): SubscribeEventFilter;

    "Unsubscribe(bytes32,tuple)"(
      subscriptionId?: PromiseOrValue<BytesLike> | null,
      subscription?: null
    ): UnsubscribeEventFilter;
    Unsubscribe(
      subscriptionId?: PromiseOrValue<BytesLike> | null,
      subscription?: null
    ): UnsubscribeEventFilter;
  };

  estimateGas: {
    VERSION(overrides?: CallOverrides): Promise<BigNumber>;

    eventsPublished(
      arg0: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    publishEvent(
      srcSlotTxSlotPack: PromiseOrValue<BytesLike>,
      receiptsRootProof: PromiseOrValue<BytesLike>[],
      receiptsRoot: PromiseOrValue<BytesLike>,
      receiptProof: PromiseOrValue<BytesLike>[],
      txIndexRLPEncoded: PromiseOrValue<BytesLike>,
      logIndex: PromiseOrValue<BigNumberish>,
      subscription: SubscriptionStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    subscribe(
      _sourceChainId: PromiseOrValue<BigNumberish>,
      _sourceAddress: PromiseOrValue<string>,
      _callbackAddress: PromiseOrValue<string>,
      _eventSig: PromiseOrValue<BytesLike>,
      _startSlot: PromiseOrValue<BigNumberish>,
      _endSlot: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    subscriptions(
      arg0: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    unsubscribe(
      _sourceChainId: PromiseOrValue<BigNumberish>,
      _sourceAddress: PromiseOrValue<string>,
      _eventSig: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    VERSION(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    eventsPublished(
      arg0: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    publishEvent(
      srcSlotTxSlotPack: PromiseOrValue<BytesLike>,
      receiptsRootProof: PromiseOrValue<BytesLike>[],
      receiptsRoot: PromiseOrValue<BytesLike>,
      receiptProof: PromiseOrValue<BytesLike>[],
      txIndexRLPEncoded: PromiseOrValue<BytesLike>,
      logIndex: PromiseOrValue<BigNumberish>,
      subscription: SubscriptionStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    subscribe(
      _sourceChainId: PromiseOrValue<BigNumberish>,
      _sourceAddress: PromiseOrValue<string>,
      _callbackAddress: PromiseOrValue<string>,
      _eventSig: PromiseOrValue<BytesLike>,
      _startSlot: PromiseOrValue<BigNumberish>,
      _endSlot: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    subscriptions(
      arg0: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    unsubscribe(
      _sourceChainId: PromiseOrValue<BigNumberish>,
      _sourceAddress: PromiseOrValue<string>,
      _eventSig: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
