/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../../common";

export interface SubscriptionReceiverInterface extends utils.Interface {
  functions: {
    "handlePublish(bytes32,uint32,address,uint64,bytes32[],bytes)": FunctionFragment;
    "pubSub()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: "handlePublish" | "pubSub"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "handlePublish",
    values: [
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>[],
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(functionFragment: "pubSub", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "handlePublish",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "pubSub", data: BytesLike): Result;

  events: {};
}

export interface SubscriptionReceiver extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: SubscriptionReceiverInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    handlePublish(
      _subscriptionId: PromiseOrValue<BytesLike>,
      _sourceChainId: PromiseOrValue<BigNumberish>,
      _sourceAddress: PromiseOrValue<string>,
      _slot: PromiseOrValue<BigNumberish>,
      _eventTopics: PromiseOrValue<BytesLike>[],
      _eventdata: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    pubSub(overrides?: CallOverrides): Promise<[string]>;
  };

  handlePublish(
    _subscriptionId: PromiseOrValue<BytesLike>,
    _sourceChainId: PromiseOrValue<BigNumberish>,
    _sourceAddress: PromiseOrValue<string>,
    _slot: PromiseOrValue<BigNumberish>,
    _eventTopics: PromiseOrValue<BytesLike>[],
    _eventdata: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  pubSub(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    handlePublish(
      _subscriptionId: PromiseOrValue<BytesLike>,
      _sourceChainId: PromiseOrValue<BigNumberish>,
      _sourceAddress: PromiseOrValue<string>,
      _slot: PromiseOrValue<BigNumberish>,
      _eventTopics: PromiseOrValue<BytesLike>[],
      _eventdata: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<string>;

    pubSub(overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    handlePublish(
      _subscriptionId: PromiseOrValue<BytesLike>,
      _sourceChainId: PromiseOrValue<BigNumberish>,
      _sourceAddress: PromiseOrValue<string>,
      _slot: PromiseOrValue<BigNumberish>,
      _eventTopics: PromiseOrValue<BytesLike>[],
      _eventdata: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    pubSub(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    handlePublish(
      _subscriptionId: PromiseOrValue<BytesLike>,
      _sourceChainId: PromiseOrValue<BigNumberish>,
      _sourceAddress: PromiseOrValue<string>,
      _slot: PromiseOrValue<BigNumberish>,
      _eventTopics: PromiseOrValue<BytesLike>[],
      _eventdata: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    pubSub(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
