/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as ethereum from "./ethereum";
export type { ethereum };
import type * as interfaces from "./interfaces";
export type { interfaces };
