/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  ILayerZeroEndpoint,
  ILayerZeroEndpointInterface,
} from "../../../contracts/interfaces/ILayerZeroEndpoint";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_userApplication",
        type: "address",
      },
    ],
    name: "getReceiveLibraryAddress",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class ILayerZeroEndpoint__factory {
  static readonly abi = _abi;
  static createInterface(): ILayerZeroEndpointInterface {
    return new utils.Interface(_abi) as ILayerZeroEndpointInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ILayerZeroEndpoint {
    return new Contract(address, _abi, signerOrProvider) as ILayerZeroEndpoint;
  }
}
