/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as loremIpsumStorageSol from "./LoremIpsumStorage.sol";
export type { loremIpsumStorageSol };
import type * as interfaces from "./interfaces";
export type { interfaces };
export type { LoremIpsumAccess } from "./LoremIpsumAccess";
export type { LoremIpsumRouter } from "./LoremIpsumRouter";
export type { SourceAMB } from "./SourceAMB";
export type { TargetAMB } from "./TargetAMB";
