/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IOracleCallbackReceiver,
  IOracleCallbackReceiverInterface,
} from "../../../../contracts/oracle/interfaces/IOracleCallbackReceiver";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "nonce",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "responseData",
        type: "bytes",
      },
      {
        internalType: "bool",
        name: "responseSuccess",
        type: "bool",
      },
    ],
    name: "handleOracleResponse",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IOracleCallbackReceiver__factory {
  static readonly abi = _abi;
  static createInterface(): IOracleCallbackReceiverInterface {
    return new utils.Interface(_abi) as IOracleCallbackReceiverInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IOracleCallbackReceiver {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IOracleCallbackReceiver;
  }
}
