/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as loremIpsumStorageSol from "./LoremIpsumStorage.sol";
export * as interfaces from "./interfaces";
export { LoremIpsumAccess__factory } from "./LoremIpsumAccess__factory";
export { LoremIpsumRouter__factory } from "./LoremIpsumRouter__factory";
export { SourceAMB__factory } from "./SourceAMB__factory";
export { TargetAMB__factory } from "./TargetAMB__factory";
