/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../common";

export interface LoremIpsumTransitionsManagerInterface extends utils.Interface {
  functions: {
    "processExecuteMessageCrossChain(uint64,uint32,address,uint32,address,bytes)": FunctionFragment;
    "processSendRequestCrossChain(uint32,address,bytes,bytes,uint256)": FunctionFragment;
    "setOracle(address)": FunctionFragment;
    "setVerifierHandler(uint32,uint256,address)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "processExecuteMessageCrossChain"
      | "processSendRequestCrossChain"
      | "setOracle"
      | "setVerifierHandler"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "processExecuteMessageCrossChain",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "processSendRequestCrossChain",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "setOracle",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "setVerifierHandler",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "processExecuteMessageCrossChain",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "processSendRequestCrossChain",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setOracle", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setVerifierHandler",
    data: BytesLike
  ): Result;

  events: {};
}

export interface LoremIpsumTransitionsManager extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: LoremIpsumTransitionsManagerInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    processExecuteMessageCrossChain(
      _nonce: PromiseOrValue<BigNumberish>,
      _sourceChainId: PromiseOrValue<BigNumberish>,
      _sourceAddress: PromiseOrValue<string>,
      _destinationChainId: PromiseOrValue<BigNumberish>,
      _destinationAddress: PromiseOrValue<string>,
      _transitionStorageRawData: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    processSendRequestCrossChain(
      _destinationChainId: PromiseOrValue<BigNumberish>,
      _targetContract: PromiseOrValue<string>,
      _targetData: PromiseOrValue<BytesLike>,
      _proof: PromiseOrValue<BytesLike>,
      _proofVerificationTypeId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setOracle(
      _oracle: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setVerifierHandler(
      _sourceChainId: PromiseOrValue<BigNumberish>,
      _proofVerificationTypeId: PromiseOrValue<BigNumberish>,
      _verifier: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  processExecuteMessageCrossChain(
    _nonce: PromiseOrValue<BigNumberish>,
    _sourceChainId: PromiseOrValue<BigNumberish>,
    _sourceAddress: PromiseOrValue<string>,
    _destinationChainId: PromiseOrValue<BigNumberish>,
    _destinationAddress: PromiseOrValue<string>,
    _transitionStorageRawData: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  processSendRequestCrossChain(
    _destinationChainId: PromiseOrValue<BigNumberish>,
    _targetContract: PromiseOrValue<string>,
    _targetData: PromiseOrValue<BytesLike>,
    _proof: PromiseOrValue<BytesLike>,
    _proofVerificationTypeId: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setOracle(
    _oracle: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setVerifierHandler(
    _sourceChainId: PromiseOrValue<BigNumberish>,
    _proofVerificationTypeId: PromiseOrValue<BigNumberish>,
    _verifier: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    processExecuteMessageCrossChain(
      _nonce: PromiseOrValue<BigNumberish>,
      _sourceChainId: PromiseOrValue<BigNumberish>,
      _sourceAddress: PromiseOrValue<string>,
      _destinationChainId: PromiseOrValue<BigNumberish>,
      _destinationAddress: PromiseOrValue<string>,
      _transitionStorageRawData: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;

    processSendRequestCrossChain(
      _destinationChainId: PromiseOrValue<BigNumberish>,
      _targetContract: PromiseOrValue<string>,
      _targetData: PromiseOrValue<BytesLike>,
      _proof: PromiseOrValue<BytesLike>,
      _proofVerificationTypeId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>;

    setOracle(
      _oracle: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    setVerifierHandler(
      _sourceChainId: PromiseOrValue<BigNumberish>,
      _proofVerificationTypeId: PromiseOrValue<BigNumberish>,
      _verifier: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    processExecuteMessageCrossChain(
      _nonce: PromiseOrValue<BigNumberish>,
      _sourceChainId: PromiseOrValue<BigNumberish>,
      _sourceAddress: PromiseOrValue<string>,
      _destinationChainId: PromiseOrValue<BigNumberish>,
      _destinationAddress: PromiseOrValue<string>,
      _transitionStorageRawData: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    processSendRequestCrossChain(
      _destinationChainId: PromiseOrValue<BigNumberish>,
      _targetContract: PromiseOrValue<string>,
      _targetData: PromiseOrValue<BytesLike>,
      _proof: PromiseOrValue<BytesLike>,
      _proofVerificationTypeId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setOracle(
      _oracle: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setVerifierHandler(
      _sourceChainId: PromiseOrValue<BigNumberish>,
      _proofVerificationTypeId: PromiseOrValue<BigNumberish>,
      _verifier: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    processExecuteMessageCrossChain(
      _nonce: PromiseOrValue<BigNumberish>,
      _sourceChainId: PromiseOrValue<BigNumberish>,
      _sourceAddress: PromiseOrValue<string>,
      _destinationChainId: PromiseOrValue<BigNumberish>,
      _destinationAddress: PromiseOrValue<string>,
      _transitionStorageRawData: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    processSendRequestCrossChain(
      _destinationChainId: PromiseOrValue<BigNumberish>,
      _targetContract: PromiseOrValue<string>,
      _targetData: PromiseOrValue<BytesLike>,
      _proof: PromiseOrValue<BytesLike>,
      _proofVerificationTypeId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setOracle(
      _oracle: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setVerifierHandler(
      _sourceChainId: PromiseOrValue<BigNumberish>,
      _proofVerificationTypeId: PromiseOrValue<BigNumberish>,
      _verifier: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
