/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type { PromiseOrValue } from "../../../common";
import type {
  EthereumLayerZeroEndpoint,
  EthereumLayerZeroEndpointInterface,
} from "../../../contracts/mocks/EthereumLayerZeroEndpoint";

const _abi = [
  {
    inputs: [
      {
        internalType: "address[]",
        name: "userApplications",
        type: "address[]",
      },
      {
        internalType: "address[]",
        name: "receiveLibraryAddress",
        type: "address[]",
      },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_userApplication",
        type: "address",
      },
    ],
    name: "getReceiveLibraryAddress",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x608060405234801561001057600080fd5b5060405161036f38038061036f83398101604081905261002f916101eb565b80518251146100785760405162461bcd60e51b81526020600482015260116024820152704c656e677468206e6f7420657175616c2160781b604482015260640160405180910390fd5b60005b8251811015610110578181815181106100965761009661024e565b60200260200101516000808584815181106100b3576100b361024e565b60200260200101516001600160a01b03166001600160a01b0316815260200190815260200160002060006101000a8154816001600160a01b0302191690836001600160a01b031602179055508061010990610264565b905061007b565b50505061028b565b634e487b7160e01b600052604160045260246000fd5b80516001600160a01b038116811461014557600080fd5b919050565b600082601f83011261015b57600080fd5b815160206001600160401b038083111561017757610177610118565b8260051b604051601f19603f8301168101818110848211171561019c5761019c610118565b6040529384528581018301938381019250878511156101ba57600080fd5b83870191505b848210156101e0576101d18261012e565b835291830191908301906101c0565b979650505050505050565b600080604083850312156101fe57600080fd5b82516001600160401b038082111561021557600080fd5b6102218683870161014a565b9350602085015191508082111561023757600080fd5b506102448582860161014a565b9150509250929050565b634e487b7160e01b600052603260045260246000fd5b60006001820161028457634e487b7160e01b600052601160045260246000fd5b5060010190565b60d6806102996000396000f3fe6080604052348015600f57600080fd5b506004361060285760003560e01c806371ba2fd614602d575b600080fd5b605660383660046072565b6001600160a01b039081166000908152602081905260409020541690565b6040516001600160a01b03909116815260200160405180910390f35b600060208284031215608357600080fd5b81356001600160a01b0381168114609957600080fd5b939250505056fea2646970667358221220fd35d33c431b6973e36a5b2f4a5b3a802277ab6de6f41cf5e7d3ab031d3bd7b664736f6c63430008100033";

type EthereumLayerZeroEndpointConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: EthereumLayerZeroEndpointConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class EthereumLayerZeroEndpoint__factory extends ContractFactory {
  constructor(...args: EthereumLayerZeroEndpointConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    userApplications: PromiseOrValue<string>[],
    receiveLibraryAddress: PromiseOrValue<string>[],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<EthereumLayerZeroEndpoint> {
    return super.deploy(
      userApplications,
      receiveLibraryAddress,
      overrides || {}
    ) as Promise<EthereumLayerZeroEndpoint>;
  }
  override getDeployTransaction(
    userApplications: PromiseOrValue<string>[],
    receiveLibraryAddress: PromiseOrValue<string>[],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(
      userApplications,
      receiveLibraryAddress,
      overrides || {}
    );
  }
  override attach(address: string): EthereumLayerZeroEndpoint {
    return super.attach(address) as EthereumLayerZeroEndpoint;
  }
  override connect(signer: Signer): EthereumLayerZeroEndpoint__factory {
    return super.connect(signer) as EthereumLayerZeroEndpoint__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): EthereumLayerZeroEndpointInterface {
    return new utils.Interface(_abi) as EthereumLayerZeroEndpointInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): EthereumLayerZeroEndpoint {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as EthereumLayerZeroEndpoint;
  }
}
